'ARBY B-2 509th BW Whiteman AFB MO',
'BATT B-2 Whiteman AFB MO',
'BEAVER B-2 Whiteman AFB MO',
'BLURB B-2B WHITEMAN AFB MO',
'BUNCH B-2, 509th Bomb Wing; Whiteman AFB MO',
'CARLO B-2 Whiteman AFB MO',
'CHAOS B-2 Whiteman AFB MO',
'DARTH B-2 509th BW, Whiteman AFB MO',
'DEATH B-2A, 509th BW, Whiteman AFB MO',
'FLOYD B-2 509 BW/393 BS Whiteman AFB MO',
'FURY B-2A 509 BW/393 BS Whiteman AFB MO',
'GELD B-2 509TH BW WHITEMAN AFB MO',
'GEOD B-2 509th BW, Whiteman AFB MO',
'GERT B-2 509th BW Whiteman AFB MO',
'GHOST B-2 Whiteman AFB MO',
'HAMMER B-2A, Whiteman AFB MO',
'JUICY B-2 509TH BW WHITEMAN AFB MO',
'KONG B-2 509th BW, Whiteman AFB MO',
'LEAHI B-2A Northrop Palmdale AF Plant 42, CA',
'LEHI B-2 412th TW, Edwards AFB, CA',
'LINDY B-2 509 BW Whiteman AFB MO',
'MANDY B-2 509th Bomb Wing; Whiteman AFB MO',
'MISTY B-2 131 BW/110th BS Whiteman AFB MO',
'PERCO B-2, Whiteman AFB MO',
'REAPER B-2A, 509th BW Whiteman AFB MO',
'ROCKY B-2 509th Operational Support Sqdn, Whiteman AFB MO',
'SARO B-2 509th Bomb Wing; Whiteman AFB MO',
'SLAYER B-2 509th BW, Whiteman AFB MO',
'SPIRIT B-2 509th BW, Whiteman AFB, MO',
'TIGER B-2 509th BW, Whiteman AFB MO',
'TORCH B-2A 509th BW Whiteman AFB',
'WONDA B-2 509th BW, Whiteman AFB MO',
'ZETA B-2 509 BW/393 BS Whiteman AFB MO',
