'ADIOS E-4B 55th Wing, Offutt AFB, NE Airborne CP',
'ALVA E-4B 55th Wing, Offutt AFB, NE Airborne CP',
'ANITA E-4B 55th Wing, Offutt AFB, NE Airborne CP',
'BAMA E-4B 55th Wing, Offutt AFB, NE Airborne CP',
'BLOKE E-4B 55th Wing, Offutt AFB, NE Airborne CP',
'BONNO E-4B 55th Wing, Offutt AFB, NE Airborne CP',
'BUST E-4B USAF/ACC 55 Wing/1ACCS OF Offut NE',
'DEFY E-4B 55th Wing, Offutt AFB, NE Airborne CP',
'EDGE E-4B 55 Wing 1 ACCS Offutt AFB NE',
'ELCID E-4B 55th Wing, Offutt AFB, NE Airborne CP',
'FATLY E-4B Airborne CP 55th Wing, Offutt AFB, NE',
'GORDO E-4B 55th Wing, Offutt AFB, NE Airborne CP',
'HEWIT E-4B 55th Wing, Offutt AFB, NE Airborne CP',
'HORSE E-4B Airborne CP 55th Wing, Offutt AFB, NE',
'HOTROD E-4B NAOC, Offutt AFB NE',
'HUGE E-4B 1ACCS Offutt AFB, NE Airborne CP',
'LEICA E-4B Airborne CP 55th Wing, Offutt AFB, NE',
'NAVEL E-4B 55th Wing, Offutt AFB, NE Airborne CP',
'NIGHTWATCH 01 E-4B Lead NAOC a/c of day, airborne CP for NCA',
'OLMIS E-4B 55th Wing, Offutt AFB, NE Airborne CP',
'POLLY E-4B 55th Wing, Offutt AFB, NE Airborne CP',
'RENT E-4B NAOC Offutt AFB NE',
'SKIP E-4B 55 Wing / 1 ACCS Offutt AFB NE',
'SPICE E-4B 55th Wing, Offutt AFB, NE Airborne CP',
'STOLE E-4B 55th Wing, Offutt AFB, NE Airborne CP',
'TANGY E-4B 55th Wing, Offutt AFB, NE Airborne CP',
'UNTIL E-4B 55th Wing, Offutt AFB, NE Airborne CP',
'UTTER E-4B 55th Wing, Offutt AFB, NE Airborne CP',
