'ALBATROSS P-3K New Zealand-RIMPAC exercise 2014',
'ARROW P-3C VP-62 NAS Jacksonville FL',
'BANSHEE UNK Noted w/USN P-3s in Caribbean area',
'BENGAL P-3C NAS JACKSONVILLE FL',
'BRICKYARD P-3C/P-8 Poseidon, deployed to Middle East/Persian Gulf.',
'BROAD ARROW P-3C VP-62 NAS Jacksonville FL',
'BUZZARD P-3C, NAS Jacksonville FL ME.',
'CLAW P-3C VP-16 “EAGLES” NAS Jacksonville. Also seen as Red Claw',
'DAGGER P-3C POSS USN OR US CUSTOMS IN CARIBBEAN DRUG INTERDICTION',
'DEEP SEA P-3C, NAS Whidbey Island WA',
'DEMON P-3C VP-40,"Fighting Marlins" NAS Whidbey Is, WA',
'DRAGON CLAW P-3C USN NAF Kadena VP Detachment',
'EAGLE P-3C, VP-16 NAS Jacksonville FL',
'EAGLE P-3C VP-9 (PD) MCAS Kaneohe Bay HI',
'FALCON ## P-3C DUTCH NAVY P-3CS DEPLOYED TO CARIBBEAN',
'FIGHTING FREDDIE P-3C NAS Jacksonville FL',
'FIGHTING TIGER P-3C VP-8 NAS Jacksonville FL',
'FINDER 7XX P-3C PROB NAS Jacksonville FL',
'GASLIGHT CP P-3 Pacific Region Ops Center (PACROC), CINCPAC HI',
'GORETEX P-3C NAS Jacksonville FL',
'GRAY KNIGHT P-3C VP-46, NAS Whidbey Island, WA',
'GREMLIN P-3C Drug interdiction mission',
'HIGH VOLTAGE Navy Duty OPS (P-3C) , Lajes AB',
'IRON MAN P-3C VP-46, NAS Whidbey Island, WA',
'KEEP TRACK CP POSS TSCC-ASSOC W/P-3Cs',
'KOA P-3 VP-47 RIMPAC exercise 2014',
'LC## P-3C NAS Jacksonville FL',
'LD## P-3C VP-10 NAS Jacksonville FL',
'LK## P-3C VP-26 NAS Jacksonville FL',
'LL## P-8 Poseidon VP-30 NAS Jacksonville FL',
'LT## P-3C VP-62 NAS Jacksonville FL',
'LANCER P-3C VP-10 “RED Lancers” NAS Jacksonville FL',
'LONE EAGLE P-3 South Korea RIMPAC exercise 2014',
'MARINER P-3C RAAF',
'MARLIN P-3C VP-40,"Fighting Marlins" NAS Whidbey Is, WA',
'MUSIC MAKER, unid, assoc w/NAS Jacksonville P-3Cs.',
'NASA 426 P-3B Wallops Flight Facility, VA--#N426NA',
'NAVY LT*** P-3C (VP-62) NAS Jacksonville FL',
'NAVY PJ*** P-3C (VP-69) Whidbey Island WA',
'NAVY PR*** P-3C/ EP-3E (VQ-1) NAS Whidbey Island WA',
'NAVY LD*** P-3C (VP-10) NAS Jacksonville FL',
'NAVY LF*** P-3C (VP-16) NAS Jacksonville FL',
'NAVY LK*** P-3C (VP-26) NAS Jacksonville FL',
'NAVY LL*** P-8 Poseidon & P-3C/ VP-3A (VP-30) NAS Jacksonville FL',
'NAVY YB*** P-3C (VP-1) NAS Whidbey Island WA',
'NAVY YD*** P-3C (VP-4) MCAS Kaneohe Bay HI',
'NAVY LA*** P-3C (VP-5) NAS Jacksonville FL',
'NAVY QE*** P-3C (VP-40) NAS Whidbey Island WA',
'NAVY LN*** P-3C (VP-45) NAS Jacksonville FL',
'NAVY LC*** P-3C (VP-8) NAS Jacksonville FL',
'NAVY PD*** P-3C (VP-9) MCAS Kaneohe Bay HI',
'NAVY JA*** P-3C (VSX-1) NAS Patuxent River MD',
'NAVY RC*** P-3C (VP-46) NAS Whidbey Island WA',
'NAVY RD*** P-3C (VP-47) MCAS Kaneohe Bay HI',
'NEPTUNE P-3C VP-8 (LC) NAS Jacksonville FL',
'NOAA N42RF WP-3D NOAA Aircraft Operations Center MacDill AFB FL',
'NOAA N43RF WP-3D NOAA Aircraft Operations Center MacDill AFB FL',
'OMNI USN P-3Cs deployed to El Salvador-working w/Blue Star on JIATF-South missions',
'PLUTO P-3C DUTCH NAVY, DEPLOYED TO CARIBBEAN',
'PRIMETIME P-3C, NAS Whidbey Island WA',
'PRO P-8 Poseidon, VP-30 NAS Jacksonville FL',
'QUARTET P-3C poss VP-26 NAS JACKSONVILLE FL',
'RAMROD Unid exercise entity assoc w/NAS Jacksonville P-3Cs',
'RANGER EP-3 VQ-1, NAS Whidbey Island WA',
'RED CLAW P-3C POSS NAS Jacksonville FL',
'REDHOOK, P-3 NAS Whidbey Island WA RIMPAC exercise 2014',
'RED TALON P-3C, VP-16 NAS Jacksonville FL (JIATF callsign)',
'RESEARCHER NP-3D VSX-1,NAS PATUXENT RIVER MD',
'RUBBER DUCK P-3C VP-47,"Golden Swordsmen" NAS KANEOHE BAY,HI',
'SCORPION P-3C DRUG INTERDICTION OPS',
'SEAGULL P-3C NAS Jacksonville FL',
'SEA LION P-3C RAAF 92 WING EDINBURGH RIMPAC exercise 2014',
'SENTINAL possible VP-30 exercise callsign NAS Jacksonville FL',
'SPARROW 01 P-3C DUTCH NAVY ACFT, DEPLOYED TO CARIBBEAN',
'SPOT P-3C VP-11, NAS Jacksonville FL, ME',
'STRAIGHT P-3 VP-65, NAS PT MUGU CA',
'STRIKER P-3C RAAF 10 Sqdn Edinburgh',
'SWORD P-3C VP-47 Kaneohe Bay HI RIMPAC exercise 2014',
'TIMBER WOLF Unid exercise entity assoc w/NAS Jacksonville P-3Cs',
'TOTEM, P-3 NAS Whidbey Island WA',
'TRIDENT P-3C VP-26 “TRIDENTS”, NAS Jacksonville FL',
'VANGUARD CONTROL, unis--assoc w/NAS Jacksonville FL P-3/P-8 acty',
'WAFER P-3C VP-10 “MINUTEMEN”, NAS Jacksonville FL (JIATF callsign)',
'WAVE RIDER P-3C',
'WHITE OWL prob P-3C, NAS Jacksonville FL',
'WILLOW P-3C VX-20 NAS Patuxent River MD',
'WRANGLER P-3C NAS Jacksonville FL',
