'ARGUS RC-12 1st MI Bn, GE',
'ARGUS RC-12 USAFE/1st MI Bn GE',
'GLARE RC-12N 224MIB (AE) Hunter AAF Savanna GA',
'RAIL RC-12P Ft Hood TX',
'RAIL RC-12, Hunter AAF, Savannah GA',
'SPARKY RC-12D, CECOM Flt ACT, poss Ft Monmouth NJ',
'SUNNY RC-12 224th Military Intelligence Bn Hunter AAF Savannah GA',
