'ADDAM T-6B USNTPS NAS Patuxent River MD',
'BOMA T-6A 37th FTW/41st FTS, Columbus AFB MS',
'BUCK T-1A/T-6 Texan II , VT-4/TAW-6, NAS Pensacola FL',
'CUTLASS T-6A 37th FTW/41st FTS, Columbus AFB MS',
'FLITE, T-6A Texan, 14th FLTW Columbus AFB SC',
'KATT T-1A/T-6 Texan II, VT-10/TAW-6, NAS Pensacola FL',
'SHOOTER T-34C, VT-6/TAW-5, NAS Whiting Field FL',
'STINE T-6A 37th FTW/41st FTS, Columbus AFB MS',
'VALOR T-6A 37th FTW/41st FTS, Columbus AFB MS',
